services:
  db:
    image: docker.io/library/mysql:latest
    container_name: flaskauth_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: flask_crud
      # Se quiser, crie um usuário diferente do root:
      # MYSQL_USER: myuser
      # MYSQL_PASSWORD: mypass
      # MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
